id: P05D44F31
initial_creation_type: input
source_metadata:
  title: Manusmṛti
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharma -- Smṛti
  data entry: Michio Yano
  contribution to GRETIL: Michio Yano
  analysis and proofreading: Michio Yano
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:28:49.090722'
last_modified_at: '2022-03-09T15:28:49.090805'
